version: '3.1'

services:

  epg:
    build:
      context: .
    env_file:
      - .env
    ports: 
      - ${EPG_PORT}:3005
    restart: always

  epgparser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    env_file:
      - .env
    ports: 
      - ${EPG_PARSER_PORT}:3005
    volumes:
      - ./epg_xml:/usr/src/app/epg_xml

  db:
    build:
      context: ./mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./db_instances:/var/lib/mysql

  
  Redis:
    image: sameersbn/redis:4.0.9-3
    ports:
      - 6380:6379
    restart: always 
  
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db
